# Generated by Django 5.1.6 on 2025-02-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('source_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('date_of_journey', models.DateField()),
            ],
        ),
    ]
