# Generated by Django 5.1.6 on 2025-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='destination_station',
            field=models.CharField(choices=[('AKOLA', 'Delhi'), ('AMRAVATI', 'Mumbai'), ('WASHIM', 'Kolkata'), ('WARUD', 'Chennai'), ('AKOT', 'Bangalore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='source_station',
            field=models.CharField(choices=[('AKOLA', 'Delhi'), ('AMRAVATI', 'Mumbai'), ('WASHIM', 'Kolkata'), ('WARUD', 'Chennai'), ('AKOT', 'Bangalore')], max_length=100),
        ),
    ]
